version: '3'
services:
  postgresdb:
    build:
      context: ./MarketPlaceDB
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    volumes:
      - ./MarketPlaceDB/db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin", "-d", "MarketPlace"]
      interval: 5s
      timeout: 5s
      retries: 20
    
    
  migrate_test:
    image: migrate/migrate
    depends_on:
      postgresdb:
        condition: service_healthy
    volumes:
        - ./MarketPlaceDB/migrations:/migrations
    command: ["-database",  "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/MarketPlaceTest?sslmode=disable", "-path", "/migrations", "up"]
    
  migrate_prod:
    image: migrate/migrate
    depends_on:
      postgresdb:
        condition: service_healthy
    volumes:
        - ./MarketPlaceDB/migrations:/migrations
    command: ["-database",  "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/MarketPlace?sslmode=disable", "-path", "/migrations", "up"]

  apiserver:
    build:
      context: ./MarketPlace
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    depends_on:
      - migrate_prod
    ports:
      - "8080:8080"

  client:
    build:
      context: ./WebClient
      dockerfile: Dockerfile
    depends_on:
      - apiserver
    ports:
      - "3000:3000"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - apiserver
      - client
    ports:
      - "80:80"

volumes:
  db_data: